Ejemplo-02/config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Ejemplo-02/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Ejemplo-02/app/models/post.rb
class Post < ApplicationRecord
end

Ejemplo-02/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Ejemplo-02/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    # Si hay una 'query', almacenar solo el contenido que sea igual a la búsqueda:
    if params[:query].present? 
      @posts = Post.where(content: params[:query])
    # En caso contrario, almacenar todos los posts:
    else
      @posts = Post.all  
    end
    
    @new_post = Post.new
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:content, :title)
    end
end

Ejemplo-02/app/helpers/application_helper.rb
module ApplicationHelper
end

Ejemplo-02/app/helpers/posts_helper.rb
module PostsHelper
end

Ejemplo-02/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ejemplo02</title>
    <%= csrf_meta_tags %>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="<%= posts_path %>">Home</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <form class="form-inline my-2 my-lg-0" action="<%= posts_path %>">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="query">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </body>
</html>

Ejemplo-02/app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= form.label :title, "Título:"%>
    <%= form.text_field :title, id: :post_title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :content, "Contenido:"%>
    <%= form.text_field :content, id: :post_content, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit "Crear Post", class: 'btn btn-primary' %>
  </div>
<% end %>

Ejemplo-02/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

Ejemplo-02/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-sm-12 col-md-7 col-lg-7">
    <% if @posts.any? %>
    <h3 class="text-info">Posts</h3>
    <ul class="list-group list-group-flush">
      <% @posts.each do |post| %>
        <li class="list-group-item">
          <div class="d-flex justify-content-start">
            <p class="font-weight-bold"><%= post.title%></p>
          </div>
          <div class="d-flex justify-content-start">
            <%= post.content %>
          </div>
          <div class="">
            <%= link_to 'Show', post, class: 'btn btn-success btn-sm' %>
            <%= link_to 'Edit', edit_post_path(post), class: 'btn btn-info btn-sm' %>
            <%= link_to 'Destroy', post, method: :delete, 
            data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
          </div>
        </li>
      <% end %>
    </ul>
    <% else %>
      <h4>No hay Post con el contenido <%= params[:query]%></h4>
    <% end %>
  </div>
    
  <div class="col-sm-12 col-md-5 col-lg-5">
    <h3 class="text-info">Nuevo Post:</h3>
    <%= render 'form', post: @new_post %>
  </div>
</div>

Ejemplo-02/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

Ejemplo-02/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>