Ejemplo-01/config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  get 'pages/about'
  root 'pages#index' # root: Definir como página principal

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Ejemplo-01/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Ejemplo-01/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Ejemplo-01/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @products = ['Producto1', 'Producto2', 'Producto3']
  end

  def about
  end
end

Ejemplo-01/app/helpers/application_helper.rb
module ApplicationHelper
end

Ejemplo-01/app/helpers/pages_helper.rb
module PagesHelper
end

Ejemplo-01/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ejemplo01</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Ejemplo-01/app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

<a href="<%= pages_index_path %>"> Ir a INDEX </a>
<p>Con "link_to":</p>
<%= link_to "Ir a INDEX", root_path %> 

Ejemplo-01/app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

<a href="<%= pages_about_path %>"> Ir a ABOUT </a>
<p>Con "link_to":</p>
<%= link_to "Ir a ABOUT", pages_about_path %> 

<% @products.each do |e| %>
  <h4><%= e %></h4>
<% end %>